### ISSUE TITLE
Using AWS Cloudfront & S3 instead of Cloudinary 

### ISSUE THREAD

**Issue by jonrrivera** [strapi/strapi-starter-blog#7]
Hi, 

This is a great starting point for the blog, but I am looking to use AWS Cloudfront & S3 for storage since its less expensive and scalable than Cloudinary. Please let me know if this is possible and if there is any way I can help. 

Thanks!

**Comment by remi2j** [comment]
You can upload your assets on S3 if you want. Do this:

* Delete the `extensions/upload` directory
* Uninstall the `strapi-provider-upload-cloudinary` package
* Install the [strapi-provider-upload-aws-s3](https://www.npmjs.com/package/strapi-provider-upload-aws-s3) package and add a config (see the readme of this package)

**Comment by jonrrivera** [comment]
@remi2j thanks for the response! I was able to follow this instruction and have this guide running locally. The problem came up when deploying to Heroku because the one-click deploy in this guide requires Cloudinary credentials.

**Comment by remi2j** [comment]
Good to know! Yes, having providers set up out of the box can be a bit confusing. That will change soon
